import { Platform, StyleSheet } from 'react-native'

export const getThemeColors = (isDark: boolean) => ({
  background: isDark ? '#111827' : '#EEF2F7',
  text: isDark ? '#E5EAF2' : '#243447',
  primary: isDark ? '#AFC9E8' : '#243B53',
  muted: isDark ? '#AAB7C8' : '#64748B',
  placeholder: isDark ? '#8796A8' : '#8A99AB',
  accent: isDark ? '#8BB8E8' : '#4F7CAC',
  danger: isDark ? '#F08A8A' : '#B43F45',
  inverse: '#FFFFFF',
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 8 : 22,
    backgroundColor: '#EEF2F7',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    minHeight: 48,
    marginBottom: 10,
    zIndex: 1,
  },
  topBarAboveOverlay: { zIndex: 2 },
  selectionCount: {
    flex: 1,
    paddingLeft: 18,
    color: '#243447',
    fontSize: 14,
    fontWeight: '700',
  },
  selectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  floatingDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: Platform.OS === 'ios' ? 12 : 8,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  recordingPanel: {
    bottom: 0,
    paddingTop: 36,
    paddingHorizontal: 0,
    paddingBottom: Platform.OS === 'ios' ? 12 : 8,
    backgroundColor: '#E5EBF2',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 7,
    shadowColor: '#182638',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.72,
    shadowRadius: 10,
  },
  topActions: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  contextMenuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  recordingContextMenu: {
    position: 'absolute',
    top: 52,
    right: 0,
    zIndex: 3,
    width: 184,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderColor: 'rgba(38,54,74,0.1)',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#182638',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  contextMenuItem: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 12,
  },
  contextMenuLabel: {
    color: '#243447',
    fontSize: 15,
    fontWeight: '500',
  },
  contextMenuDeleteLabel: {
    color: '#B43F45',
    fontSize: 15,
    fontWeight: '500',
  },
  contextMenuDivider: {
    height: 1,
    marginHorizontal: 12,
    backgroundColor: '#E8EDF3',
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  circleButtonRight: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  circleButtonLeft: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  searchInput: {
    flex: 1,
    height: 50,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.82)',
    paddingHorizontal: 16,
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    fontSize: 15,
    color: '#26364A',
  },
  pageTitle: {
    color: '#26364A',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '800',
    marginLeft: 18,
    marginTop: 14,
    marginBottom: 14,
  },
  compactPageTitle: {
    flex: 1,
    marginLeft: 18,
    color: '#26364A',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '800',
  },
  eyebrow: {
    color: '#647D98',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 5,
  },
  homeSearchContainer: {
    width: '100%',
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.78)',
    paddingHorizontal: 12,
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    marginBottom: 14,
  },
  homeSearchInput: {
    height: 48,
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 15,
    color: '#26364A',
  },
  button: {
    alignSelf: 'flex-start',
    backgroundColor: '#243B53',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  buttonText: { fontSize: 14, fontWeight: '600', color: 'white' },
  recordingsList: { flex: 1 },
  recordingItem: {
    marginBottom: 12,
    padding: 17,
    minWidth: 0,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    width: '100%',
  },
  recordingItemSelected: {
    backgroundColor: '#E5EBF2',
    borderColor: '#243B53',
  },
  recordingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  recordingName: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: '700',
    color: '#243447',
  },
  recordingFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 2,
  },
  recordingDetails: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    color: '#64748B',
  },
  recordingDuration: {
    maxWidth: '45%',
    minWidth: 0,
    marginLeft: 8,
    flexShrink: 1,
    color: '#64748B',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
    textAlign: 'right',
  },
  recordingDetailTitle: {
    flex: 1,
    marginHorizontal: 10,
    color: '#243447',
    fontSize: 17,
    fontWeight: '700',
  },
  emptyState: {
    flex: 1,
    minHeight: 200,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeEmptyState: {
    transform: [{ translateY: -20 }],
  },
  emptyIllustration: {
    width: 176,
    height: 176,
    marginBottom: 18,
  },
  emptyTitle: {
    alignSelf: 'stretch',
    flexShrink: 1,
    color: '#64748B',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '500',
    textAlign: 'center',
  },
  dockContent: {
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
  },
  dockLabel: {
    color: '#243447',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
    textAlign: 'center',
  },
  dockSubtitle: {
    color: '#64748B',
    fontSize: 14,
    marginTop: 4,
    marginBottom: 12,
    textAlign: 'center',
  },
  micControl: {
    width: 84,
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  micButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#243B53',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  micButtonDisabled: { opacity: 0.45 },
  pulseRing: {
    position: 'absolute',
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 1,
    borderColor: '#6D9DD0',
  },
  waveform: {
    width: '100%',
    height: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 4,
    marginBottom: 8,
  },
  waveformBar: {
    width: 4,
    minHeight: 4,
    maxHeight: 58,
    borderRadius: 3,
    backgroundColor: '#4F7CAC',
  },
  scrollableTextBox: {
    flex: 1,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    width: '100%',
    marginBottom: 14,
  },
  miniPlayer: {
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 24,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'stretch',
    marginBottom: Platform.OS === 'ios' ? 12 : 18,
  },
  playbackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  playbackSkipButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playbackSkipLabel: {
    position: 'absolute',
    top: 19,
    right: 0,
    left: 0,
    color: '#243B53',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
    textAlign: 'center',
  },
  playbackSeekArea: {
    height: 32,
    justifyContent: 'center',
    marginTop: 10,
  },
  playbackTrack: {
    height: 4,
    backgroundColor: '#D7E0EA',
    borderRadius: 2,
    overflow: 'hidden',
  },
  playbackTrackFill: {
    height: '100%',
    backgroundColor: '#4F7CAC',
  },
  playbackThumb: {
    position: 'absolute',
    top: 9,
    width: 14,
    height: 14,
    marginLeft: -7,
    borderRadius: 7,
    backgroundColor: '#243B53',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 2,
  },
  playbackTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  playbackTime: {
    color: '#64748B',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  playerButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#243B53',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: 'transparent',
  },
  renameModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20,30,46,0.42)',
  },
  renameModal: {
    padding: 20,
    backgroundColor:
      Platform.OS === 'android' ? '#FFFFFF' : 'rgba(255,255,255,0.78)',
    borderRadius: 20,
  },
  renameInput: {
    height: 48,
    marginTop: 16,
    marginBottom: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#D7E0EA',
    borderRadius: 12,
    color: '#26364A',
    fontSize: 16,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalSecondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: '#E8EDF3',
  },
  modalSecondaryButtonText: {
    color: '#243B53',
    fontSize: 14,
    fontWeight: '600',
  },
  outputText: {
    paddingTop: 10,
    fontSize: 16,
    lineHeight: 25,
    color: '#243447',
  },
  settingsTitle: { fontSize: 22, fontWeight: '700', color: '#243447' },
  settingsHeaderSpacer: { width: 48, height: 48 },
  settingsBackButton: { marginRight: 0 },
  appInfo: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
  },
  settingsContent: { flex: 1, paddingTop: 16 },
  settingsSection: { marginBottom: 28 },
  settingsSectionTitle: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 10,
    marginLeft: 12,
  },
  settingsOptionGroup: {
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  settingsOptionRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  settingsOptionIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    backgroundColor: '#E6EDF5',
    borderRadius: 13,
  },
  settingsOptionLabel: {
    flex: 1,
    color: '#64748B',
    fontSize: 16,
    fontWeight: '500',
  },
  settingsOptionLabelSelected: {
    color: '#243447',
    fontWeight: '600',
  },
  settingsOptionDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: 68,
    backgroundColor: '#E4EAF1',
  },
  settingsRadio: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#B6C2D0',
    borderRadius: 11,
  },
  settingsRadioSelected: {
    borderColor: '#4F7CAC',
    backgroundColor: '#4F7CAC',
  },
  settingsRadioDot: {
    width: 8,
    height: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
  },
  languageCode: {
    minWidth: 38,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    paddingHorizontal: 6,
    backgroundColor: '#E6EDF5',
    borderRadius: 12,
  },
  languageCodeText: {
    color: '#4F7CAC',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  appearanceDescription: {
    color: '#64748B',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 10,
    paddingHorizontal: 12,
  },
  appInfoIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E6EDF5',
  },
  appInfoCopy: { flex: 1, minWidth: 0 },
  appInfoTitle: { color: '#243447', fontSize: 16, fontWeight: '700' },
  appInfoDetail: { color: '#64748B', fontSize: 13, marginTop: 3 },
  appInfoVersion: { color: '#64748B', fontSize: 12 },
})

const darkStyles = {
  ...styles,
  container: [styles.container, { backgroundColor: '#111827' }],
  selectionCount: [styles.selectionCount, { color: '#E5EAF2' }],
  recordingPanel: [styles.recordingPanel, { backgroundColor: '#182333' }],
  recordingContextMenu: [
    styles.recordingContextMenu,
    { backgroundColor: '#1B2738', borderColor: '#34445A' },
  ],
  contextMenuLabel: [styles.contextMenuLabel, { color: '#E5EAF2' }],
  contextMenuDivider: [
    styles.contextMenuDivider,
    { backgroundColor: '#34445A' },
  ],
  iconButton: [
    styles.iconButton,
    { backgroundColor: '#222F42', borderColor: '#34445A' },
  ],
  circleButtonRight: [
    styles.circleButtonRight,
    { backgroundColor: '#222F42', borderColor: '#34445A' },
  ],
  circleButtonLeft: [
    styles.circleButtonLeft,
    { backgroundColor: '#222F42', borderColor: '#34445A' },
  ],
  searchInput: [
    styles.searchInput,
    { backgroundColor: '#222F42', borderColor: '#34445A', color: '#E5EAF2' },
  ],
  pageTitle: [styles.pageTitle, { color: '#E5EAF2' }],
  compactPageTitle: [styles.compactPageTitle, { color: '#E5EAF2' }],
  eyebrow: [styles.eyebrow, { color: '#AAB7C8' }],
  homeSearchContainer: [
    styles.homeSearchContainer,
    { backgroundColor: '#222F42', borderColor: '#34445A' },
  ],
  homeSearchInput: [styles.homeSearchInput, { color: '#E5EAF2' }],
  button: [styles.button, { backgroundColor: '#4F7CAC' }],
  recordingItem: [
    styles.recordingItem,
    { backgroundColor: '#1B2738', borderColor: '#34445A' },
  ],
  recordingItemSelected: [
    styles.recordingItemSelected,
    { backgroundColor: '#2A3A50', borderColor: '#8BB8E8' },
  ],
  recordingName: [styles.recordingName, { color: '#E5EAF2' }],
  recordingDetails: [styles.recordingDetails, { color: '#AAB7C8' }],
  recordingDuration: [styles.recordingDuration, { color: '#AAB7C8' }],
  recordingDetailTitle: [styles.recordingDetailTitle, { color: '#E5EAF2' }],
  emptyTitle: [styles.emptyTitle, { color: '#AAB7C8' }],
  dockLabel: [styles.dockLabel, { color: '#E5EAF2' }],
  dockSubtitle: [styles.dockSubtitle, { color: '#AAB7C8' }],
  micButton: [styles.micButton, { backgroundColor: '#4F7CAC' }],
  pulseRing: [styles.pulseRing, { borderColor: '#8BB8E8' }],
  waveformBar: [styles.waveformBar, { backgroundColor: '#8BB8E8' }],
  scrollableTextBox: [
    styles.scrollableTextBox,
    { backgroundColor: '#1B2738', borderColor: '#34445A' },
  ],
  miniPlayer: [
    styles.miniPlayer,
    { backgroundColor: '#1B2738', borderColor: '#34445A' },
  ],
  playbackTrack: [styles.playbackTrack, { backgroundColor: '#3A4A60' }],
  playbackTrackFill: [styles.playbackTrackFill, { backgroundColor: '#8BB8E8' }],
  playbackThumb: [
    styles.playbackThumb,
    { backgroundColor: '#8BB8E8', borderColor: '#1B2738' },
  ],
  playbackTime: [styles.playbackTime, { color: '#AAB7C8' }],
  playerButton: [styles.playerButton, { backgroundColor: '#4F7CAC' }],
  renameModalBackdrop: [
    styles.renameModalBackdrop,
    { backgroundColor: 'rgba(0,0,0,0.64)' },
  ],
  renameModal: [styles.renameModal, { backgroundColor: '#1B2738' }],
  renameInput: [
    styles.renameInput,
    { backgroundColor: '#222F42', borderColor: '#46566C', color: '#E5EAF2' },
  ],
  modalSecondaryButton: [
    styles.modalSecondaryButton,
    { backgroundColor: '#34445A' },
  ],
  modalSecondaryButtonText: [
    styles.modalSecondaryButtonText,
    { color: '#E5EAF2' },
  ],
  outputText: [styles.outputText, { color: '#E5EAF2' }],
  settingsTitle: [styles.settingsTitle, { color: '#E5EAF2' }],
  settingsSectionTitle: [styles.settingsSectionTitle, { color: '#AAB7C8' }],
  appInfo: [
    styles.appInfo,
    { backgroundColor: '#1B2738', borderColor: '#34445A' },
  ],
  appInfoIcon: [styles.appInfoIcon, { backgroundColor: '#2A3A50' }],
  settingsOptionGroup: [
    styles.settingsOptionGroup,
    { backgroundColor: '#1B2738', borderColor: '#34445A' },
  ],
  settingsOptionIcon: [
    styles.settingsOptionIcon,
    { backgroundColor: '#2A3A50' },
  ],
  settingsOptionLabel: [
    styles.settingsOptionLabel,
    { color: '#AAB7C8' },
  ],
  settingsOptionLabelSelected: [
    styles.settingsOptionLabelSelected,
    { color: '#E5EAF2' },
  ],
  settingsOptionDivider: [
    styles.settingsOptionDivider,
    { backgroundColor: '#34445A' },
  ],
  settingsRadio: [
    styles.settingsRadio,
    { borderColor: '#68778D' },
  ],
  settingsRadioSelected: [
    styles.settingsRadioSelected,
    { borderColor: '#8BB8E8', backgroundColor: '#8BB8E8' },
  ],
  languageCode: [
    styles.languageCode,
    { backgroundColor: '#2A3A50' },
  ],
  languageCodeText: [styles.languageCodeText, { color: '#8BB8E8' }],
  appearanceDescription: [styles.appearanceDescription, { color: '#AAB7C8' }],
  appInfoTitle: [styles.appInfoTitle, { color: '#E5EAF2' }],
  appInfoDetail: [styles.appInfoDetail, { color: '#AAB7C8' }],
  appInfoVersion: [styles.appInfoVersion, { color: '#AAB7C8' }],
}

export const getStyles = (isDark: boolean) => (isDark ? darkStyles : styles)

export default styles
