import { Platform, StyleSheet } from 'react-native'

export const getThemeColors = (isDark: boolean) => ({
  background: isDark ? '#101B1E' : '#EAF1EE',
  text: isDark ? '#E5EFED' : '#18363C',
  primary: isDark ? '#A4D8CE' : '#173C43',
  muted: isDark ? '#A0B5B3' : '#60777A',
  placeholder: isDark ? '#819896' : '#82989A',
  accent: isDark ? '#76C5B6' : '#32877F',
  danger: isDark ? '#F08A8A' : '#B43F45',
  inverse: '#FFFFFF',
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 8 : 22,
    backgroundColor: '#EAF1EE',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    minHeight: 48,
    marginBottom: 10,
    zIndex: 1,
  },
  topBarAboveOverlay: { zIndex: 2 },
  selectionCount: {
    flex: 1,
    paddingLeft: 18,
    color: '#18363C',
    fontSize: 14,
    fontWeight: '700',
  },
  selectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  floatingDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: Platform.OS === 'ios' ? 12 : 8,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  recordingPanel: {
    bottom: 0,
    paddingTop: 36,
    paddingHorizontal: 0,
    paddingBottom: Platform.OS === 'ios' ? 12 : 8,
    backgroundColor: '#E8EDED',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 7,
    shadowColor: '#162D34',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.72,
    shadowRadius: 10,
  },
  topActions: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  contextMenuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  recordingContextMenu: {
    position: 'absolute',
    top: 52,
    right: 0,
    zIndex: 3,
    width: 184,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderColor: 'rgba(22,45,52,0.1)',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#162D34',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  contextMenuItem: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 12,
  },
  contextMenuLabel: {
    color: '#18363C',
    fontSize: 15,
    fontWeight: '500',
  },
  contextMenuDeleteLabel: {
    color: '#B43F45',
    fontSize: 15,
    fontWeight: '500',
  },
  contextMenuDivider: {
    height: 1,
    marginHorizontal: 12,
    backgroundColor: '#EAF0EF',
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  circleButtonRight: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  circleButtonLeft: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
  },
  searchInput: {
    flex: 1,
    height: 50,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.82)',
    paddingHorizontal: 16,
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    fontSize: 15,
    color: '#162D34',
  },
  pageTitle: {
    color: '#162D34',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '800',
    marginLeft: 18,
    marginTop: 14,
    marginBottom: 14,
  },
  compactPageTitle: {
    flex: 1,
    marginLeft: 18,
    color: '#162D34',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '800',
  },
  eyebrow: {
    color: '#547579',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 5,
  },
  homeSearchContainer: {
    width: '100%',
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.78)',
    paddingHorizontal: 12,
    borderColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    marginBottom: 14,
  },
  homeSearchInput: {
    height: 48,
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 15,
    color: '#162D34',
  },
  button: {
    alignSelf: 'flex-start',
    backgroundColor: '#173C43',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  buttonText: { fontSize: 14, fontWeight: '600', color: 'white' },
  recordingsList: { flex: 1 },
  recordingItem: {
    marginBottom: 12,
    padding: 17,
    minWidth: 0,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    width: '100%',
  },
  recordingItemSelected: {
    backgroundColor: '#E8EDED',
    borderColor: '#173C43',
  },
  recordingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  recordingName: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: '700',
    color: '#18363C',
  },
  recordingFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 2,
  },
  recordingDetails: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    color: '#60777A',
  },
  recordingDuration: {
    maxWidth: '45%',
    minWidth: 0,
    marginLeft: 8,
    flexShrink: 1,
    color: '#60777A',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
    textAlign: 'right',
  },
  recordingDetailTitle: {
    flex: 1,
    marginHorizontal: 10,
    color: '#18363C',
    fontSize: 17,
    fontWeight: '700',
  },
  emptyState: {
    flex: 1,
    minHeight: 200,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyStateCard: {
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
    padding: 22,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
  },
  emptyIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(255,255,255,0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    alignSelf: 'stretch',
    flexShrink: 1,
    color: '#18363C',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    alignSelf: 'stretch',
    flexShrink: 1,
    color: '#60777A',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 6,
  },
  dockContent: {
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
  },
  dockLabel: {
    color: '#18363C',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
    textAlign: 'center',
  },
  dockSubtitle: {
    color: '#60777A',
    fontSize: 14,
    marginTop: 4,
    marginBottom: 12,
    textAlign: 'center',
  },
  micControl: {
    width: 84,
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  micButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#173C43',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  micButtonDisabled: { opacity: 0.45 },
  pulseRing: {
    position: 'absolute',
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 1,
    borderColor: '#328D83',
  },
  waveform: {
    width: '100%',
    height: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 4,
    marginBottom: 8,
  },
  waveformBar: {
    width: 4,
    minHeight: 4,
    maxHeight: 58,
    borderRadius: 3,
    backgroundColor: '#31877F',
  },
  scrollableTextBox: {
    flex: 1,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    width: '100%',
    marginBottom: 14,
  },
  miniPlayer: {
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 24,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'stretch',
    marginBottom: Platform.OS === 'ios' ? 12 : 18,
  },
  playbackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  playbackSkipButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playbackSkipLabel: {
    position: 'absolute',
    top: 19,
    right: 0,
    left: 0,
    color: '#173C43',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
    textAlign: 'center',
  },
  playbackSeekArea: {
    height: 32,
    justifyContent: 'center',
    marginTop: 10,
  },
  playbackTrack: {
    height: 4,
    backgroundColor: '#D8E2E2',
    borderRadius: 2,
    overflow: 'hidden',
  },
  playbackTrackFill: {
    height: '100%',
    backgroundColor: '#32877F',
  },
  playbackThumb: {
    position: 'absolute',
    top: 9,
    width: 14,
    height: 14,
    marginLeft: -7,
    borderRadius: 7,
    backgroundColor: '#173C43',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 2,
  },
  playbackTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  playbackTime: {
    color: '#60777A',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  playerButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#173C43',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: 'rgba(15,35,38,0.42)',
  },
  renameModal: {
    padding: 20,
    backgroundColor:
      Platform.OS === 'android' ? '#FFFFFF' : 'rgba(255,255,255,0.78)',
    borderRadius: 20,
  },
  renameInput: {
    height: 48,
    marginTop: 16,
    marginBottom: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#D8E2E2',
    borderRadius: 12,
    color: '#162D34',
    fontSize: 16,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalSecondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: '#EAF0EF',
  },
  modalSecondaryButtonText: {
    color: '#173C43',
    fontSize: 14,
    fontWeight: '600',
  },
  outputText: {
    paddingTop: 10,
    fontSize: 16,
    lineHeight: 25,
    color: '#18363C',
  },
  settingsTitle: { fontSize: 22, fontWeight: '700', color: '#18363C' },
  settingsHeaderSpacer: { width: 48, height: 48 },
  settingsBackButton: { marginRight: 0 },
  appInfo: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 16,
    borderColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
  },
  settingsContent: { flex: 1, paddingTop: 12 },
  settingsSection: { marginBottom: 24 },
  settingsSectionTitle: {
    color: '#60777A',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginLeft: 4,
  },
  appearanceCard: {
    flexDirection: 'row',
    padding: 4,
    backgroundColor: '#DDE6E3',
    borderRadius: 12,
  },
  appearanceOption: {
    flex: 1,
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 6,
    borderRadius: 9,
  },
  appearanceOptionSelected: { backgroundColor: '#FFFFFF' },
  appearanceOptionText: {
    color: '#60777A',
    fontSize: 13,
    fontWeight: '600',
  },
  appearanceOptionTextSelected: { color: '#173C43' },
  appearanceDescription: {
    color: '#60777A',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 9,
    paddingHorizontal: 4,
  },
  appInfoIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E3EFEC',
  },
  appInfoCopy: { flex: 1, minWidth: 0 },
  appInfoTitle: { color: '#18363C', fontSize: 16, fontWeight: '700' },
  appInfoDetail: { color: '#60777A', fontSize: 13, marginTop: 3 },
  appInfoVersion: { color: '#60777A', fontSize: 12 },
})

const darkStyles = {
  ...styles,
  container: [styles.container, { backgroundColor: '#101B1E' }],
  selectionCount: [styles.selectionCount, { color: '#E5EFED' }],
  recordingPanel: [styles.recordingPanel, { backgroundColor: '#1B2B2E' }],
  recordingContextMenu: [
    styles.recordingContextMenu,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  contextMenuLabel: [styles.contextMenuLabel, { color: '#E5EFED' }],
  contextMenuDivider: [
    styles.contextMenuDivider,
    { backgroundColor: '#34494B' },
  ],
  iconButton: [
    styles.iconButton,
    { backgroundColor: '#223437', borderColor: '#34494B' },
  ],
  circleButtonRight: [
    styles.circleButtonRight,
    { backgroundColor: '#223437', borderColor: '#34494B' },
  ],
  circleButtonLeft: [
    styles.circleButtonLeft,
    { backgroundColor: '#223437', borderColor: '#34494B' },
  ],
  searchInput: [
    styles.searchInput,
    { backgroundColor: '#223437', borderColor: '#34494B', color: '#E5EFED' },
  ],
  pageTitle: [styles.pageTitle, { color: '#E5EFED' }],
  compactPageTitle: [styles.compactPageTitle, { color: '#E5EFED' }],
  eyebrow: [styles.eyebrow, { color: '#A0B5B3' }],
  homeSearchContainer: [
    styles.homeSearchContainer,
    { backgroundColor: '#223437', borderColor: '#34494B' },
  ],
  homeSearchInput: [styles.homeSearchInput, { color: '#E5EFED' }],
  button: [styles.button, { backgroundColor: '#32877F' }],
  recordingItem: [
    styles.recordingItem,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  recordingItemSelected: [
    styles.recordingItemSelected,
    { backgroundColor: '#293C3F', borderColor: '#76C5B6' },
  ],
  recordingName: [styles.recordingName, { color: '#E5EFED' }],
  recordingDetails: [styles.recordingDetails, { color: '#A0B5B3' }],
  recordingDuration: [styles.recordingDuration, { color: '#A0B5B3' }],
  recordingDetailTitle: [styles.recordingDetailTitle, { color: '#E5EFED' }],
  emptyStateCard: [
    styles.emptyStateCard,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  emptyIcon: [styles.emptyIcon, { backgroundColor: '#293C3F' }],
  emptyTitle: [styles.emptyTitle, { color: '#E5EFED' }],
  emptyDescription: [styles.emptyDescription, { color: '#A0B5B3' }],
  dockLabel: [styles.dockLabel, { color: '#E5EFED' }],
  dockSubtitle: [styles.dockSubtitle, { color: '#A0B5B3' }],
  micButton: [styles.micButton, { backgroundColor: '#32877F' }],
  pulseRing: [styles.pulseRing, { borderColor: '#76C5B6' }],
  waveformBar: [styles.waveformBar, { backgroundColor: '#76C5B6' }],
  scrollableTextBox: [
    styles.scrollableTextBox,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  miniPlayer: [
    styles.miniPlayer,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  playbackTrack: [styles.playbackTrack, { backgroundColor: '#3A5153' }],
  playbackTrackFill: [styles.playbackTrackFill, { backgroundColor: '#76C5B6' }],
  playbackThumb: [
    styles.playbackThumb,
    { backgroundColor: '#76C5B6', borderColor: '#1D2D30' },
  ],
  playbackTime: [styles.playbackTime, { color: '#A0B5B3' }],
  playerButton: [styles.playerButton, { backgroundColor: '#32877F' }],
  modalBackdrop: [
    styles.modalBackdrop,
    { backgroundColor: 'rgba(0,0,0,0.64)' },
  ],
  renameModal: [styles.renameModal, { backgroundColor: '#1D2D30' }],
  renameInput: [
    styles.renameInput,
    { backgroundColor: '#223437', borderColor: '#405759', color: '#E5EFED' },
  ],
  modalSecondaryButton: [
    styles.modalSecondaryButton,
    { backgroundColor: '#34494B' },
  ],
  modalSecondaryButtonText: [
    styles.modalSecondaryButtonText,
    { color: '#E5EFED' },
  ],
  outputText: [styles.outputText, { color: '#E5EFED' }],
  settingsTitle: [styles.settingsTitle, { color: '#E5EFED' }],
  settingsSectionTitle: [styles.settingsSectionTitle, { color: '#A0B5B3' }],
  appInfo: [
    styles.appInfo,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  appInfoIcon: [styles.appInfoIcon, { backgroundColor: '#293C3F' }],
  appearanceCard: [
    styles.appearanceCard,
    { backgroundColor: '#1D2D30', borderColor: '#34494B' },
  ],
  appearanceOptionSelected: [
    styles.appearanceOptionSelected,
    { backgroundColor: '#405457' },
  ],
  appearanceOptionText: [styles.appearanceOptionText, { color: '#A0B5B3' }],
  appearanceOptionTextSelected: [
    styles.appearanceOptionTextSelected,
    { color: '#E5EFED' },
  ],
  appearanceDescription: [styles.appearanceDescription, { color: '#A0B5B3' }],
  appInfoTitle: [styles.appInfoTitle, { color: '#E5EFED' }],
  appInfoDetail: [styles.appInfoDetail, { color: '#A0B5B3' }],
  appInfoVersion: [styles.appInfoVersion, { color: '#A0B5B3' }],
}

export const getStyles = (isDark: boolean) => (isDark ? darkStyles : styles)

export default styles
