import { Platform, StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 8 : 22,
    backgroundColor: 'transparent',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    minHeight: 48,
    marginBottom: 10,
    zIndex: 1,
  },
  headerFade: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? -8 : -22,
    left: -12,
    right: -12,
    height: 160,
  },
  headerFadeBand: { flex: 1, backgroundColor: '#FFFFFF' },
  topBarAboveOverlay: { zIndex: 2 },
  selectionCount: {
    flex: 1,
    paddingLeft: 18,
    color: '#18363C',
    fontSize: 14,
    fontWeight: '700',
  },
  selectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  floatingDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: Platform.OS === 'ios' ? 12 : 8,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  recordingPanel: {
    bottom: 0,
    paddingBottom: Platform.OS === 'ios' ? 12 : 8,
    backgroundColor: '#E8EDED',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 7,
    shadowColor: '#162D34',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
  },
  topActions: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  contextMenuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  recordingContextMenu: {
    position: 'absolute',
    top: 52,
    right: 0,
    zIndex: 3,
    width: 184,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderColor: 'rgba(22,45,52,0.1)',
    borderWidth: 1,
    elevation: 8,
    shadowColor: '#162D34',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  contextMenuItem: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 12,
  },
  contextMenuLabel: {
    color: '#18363C',
    fontSize: 15,
    fontWeight: '500',
  },
  contextMenuDeleteLabel: {
    color: '#B43F45',
    fontSize: 15,
    fontWeight: '500',
  },
  contextMenuDivider: {
    height: 1,
    marginHorizontal: 12,
    backgroundColor: '#EAF0EF',
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
  },
  circleButtonRight: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
  },
  circleButtonLeft: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
  },
  searchInput: {
    flex: 1,
    height: 50,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.68)',
    paddingHorizontal: 16,
    borderColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    fontSize: 15,
    color: '#162D34',
  },
  pageTitle: { color: '#162D34', fontSize: 30, fontWeight: '700' },
  eyebrow: {
    color: '#547579',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 5,
  },
  sectionHeading: { marginBottom: 18, paddingHorizontal: 18 },
  homeSearchContainer: {
    flex: 1,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.68)',
    paddingHorizontal: 12,
    borderColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    marginRight: 10,
  },
  homeSearchInput: {
    height: 48,
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 15,
    color: '#162D34',
  },
  button: {
    alignSelf: 'flex-start',
    backgroundColor: '#173C43',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  buttonText: { fontSize: 14, fontWeight: '600', color: 'white' },
  recordingsList: { flex: 1 },
  recordingItem: {
    marginBottom: 12,
    padding: 17,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.95)',
    borderWidth: 1,
    width: '100%',
  },
  recordingItemSelected: {
    backgroundColor: '#E8EDED',
    borderColor: '#173C43',
  },
  recordingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  recordingName: { fontSize: 16, fontWeight: '700', color: '#18363C' },
  recordingFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  recordingDetails: { flex: 1, fontSize: 13, color: '#60777A' },
  recordingDuration: {
    marginLeft: 12,
    color: '#60777A',
    fontSize: 13,
    fontVariant: ['tabular-nums'],
  },
  recordingsCount: { fontSize: 13, color: '#60777A', marginTop: 4 },
  recordingDetailTitle: {
    flex: 1,
    marginHorizontal: 10,
    color: '#18363C',
    fontSize: 17,
    fontWeight: '700',
  },
  emptyState: {
    flex: 1,
    minHeight: 200,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  emptyIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(255,255,255,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: { color: '#18363C', fontSize: 17, fontWeight: '700' },
  emptyDescription: {
    color: '#60777A',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 6,
  },
  dockContent: {
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
  },
  dockLabel: {
    color: '#18363C',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  dockSubtitle: {
    color: '#60777A',
    fontSize: 12,
    marginTop: 3,
    marginBottom: 10,
    textAlign: 'center',
  },
  micControl: {
    width: 84,
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  micButton: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#173C43',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  micButtonDisabled: { opacity: 0.45 },
  pulseRing: {
    position: 'absolute',
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 1,
    borderColor: '#328D83',
  },
  waveform: {
    width: '100%',
    height: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 4,
    marginBottom: 2,
  },
  waveformBar: {
    width: 4,
    minHeight: 4,
    maxHeight: 58,
    borderRadius: 3,
    backgroundColor: '#31877F',
  },
  scrollableTextBox: {
    flex: 1,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderRadius: 22,
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    width: '100%',
    marginBottom: 14,
  },
  miniPlayer: {
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderRadius: 24,
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'stretch',
    marginBottom: Platform.OS === 'ios' ? 12 : 18,
  },
  playbackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  playbackSkipButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playbackSkipLabel: {
    position: 'absolute',
    top: 19,
    right: 0,
    left: 0,
    color: '#173C43',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
    textAlign: 'center',
  },
  playbackSeekArea: {
    height: 32,
    justifyContent: 'center',
    marginTop: 10,
  },
  playbackTrack: {
    height: 4,
    backgroundColor: '#D8E2E2',
    borderRadius: 2,
    overflow: 'hidden',
  },
  playbackTrackFill: {
    height: '100%',
    backgroundColor: '#32877F',
  },
  playbackThumb: {
    position: 'absolute',
    top: 9,
    width: 14,
    height: 14,
    marginLeft: -7,
    borderRadius: 7,
    backgroundColor: '#173C43',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 2,
  },
  playbackTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  playbackTime: {
    color: '#60777A',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  playerButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#173C43',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: 'rgba(15,35,38,0.42)',
  },
  renameModal: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
  },
  renameInput: {
    height: 48,
    marginTop: 16,
    marginBottom: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#D8E2E2',
    borderRadius: 12,
    color: '#162D34',
    fontSize: 16,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalSecondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: '#EAF0EF',
  },
  modalSecondaryButtonText: {
    color: '#173C43',
    fontSize: 14,
    fontWeight: '600',
  },
  outputText: {
    paddingTop: 10,
    fontSize: 16,
    lineHeight: 25,
    color: '#18363C',
  },
  settingsTitle: { fontSize: 22, fontWeight: '700', color: '#18363C' },
  appInfo: {
    padding: 20,
    backgroundColor: 'rgba(255,255,255,0.66)',
    borderRadius: 20,
    borderColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
  },
  appInfoDetail: { color: '#60777A', fontSize: 14, marginTop: 6 },
})

export default styles
